**Realizando a conexão com o MongoDB**

In [ ]:
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://xxxxx@xxxxx.nmliqsg.mongodb.net/?retryWrites=true&w=majority&appName=xxxxx"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

## Lendo os dados no MongoDB

In [2]:
db = client["db_produtos"]
collection = db["produtos"]

In [3]:
for doc in collection.find():
    print(doc)

{'_id': ObjectId('6897d80622441912739d6bff'), 'Produto': 'Modelagem preditiva', 'Categoria do Produto': 'livros', 'Preço': 92.45, 'Frete': 5.6096965236, 'Data da Compra': '01/01/2020', 'Vendedor': 'Thiago Silva', 'Local da compra': 'BA', 'Avaliação da compra': 1, 'Tipo de pagamento': 'cartao_credito', 'Quantidade de parcelas': 3, 'Latitude': -13.29, 'Longitude': -41.71}
{'_id': ObjectId('6897d80622441912739d6c00'), 'Produto': 'Iniciando em programação', 'Categoria do Produto': 'livros', 'Preço': 43.84, 'Frete': 0.0, 'Data da Compra': '01/01/2020', 'Vendedor': 'Mariana Ferreira', 'Local da compra': 'SP', 'Avaliação da compra': 5, 'Tipo de pagamento': 'cartao_credito', 'Quantidade de parcelas': 1, 'Latitude': -22.19, 'Longitude': -48.79}
{'_id': ObjectId('6897d80622441912739d6c01'), 'Produto': 'Pandeiro', 'Categoria do Produto': 'instrumentos musicais', 'Preço': 87.18, 'Frete': 2.2265117938, 'Data da Compra': '01/01/2020', 'Vendedor': 'Thiago Silva', 'Local da compra': 'RJ', 'Avaliação da compra': 4, 'Tipo de pagamento': 'cartao_credito', 'Quantidade de parcelas': 4, 'Latitude': -22.25, 'Longitude': -42.66}
{'_id': ObjectId('6897d80622441912739d6c02'), 'Produto': 'Corda de pular', 'Categoria do Produto': 'esporte e lazer', 'Preço': 13.65, 'Frete': 1.2579259604, 'Data da Compra': '01/01/2020', 'Vendedor': 'Camila Ribeiro', 'Local da compra': 'RJ', 'Avaliação da compra': 4, 'Tipo de pagamento': 'boleto', 'Quantidade de parcelas': 1, 'Latitude': -22.25, 'Longitude': -42.66}
{'_id': ObjectId('6897d80622441912739d6c03'), 'Produto': 'Dinossauro Rex', 'Categoria do Produto': 'brinquedos', 'Preço': 28.32, 'Frete': 2.0390593271, 'Data da Compra': '01/01/2020', 'Vendedor': 'Juliana Costa', 'Local da compra': 'RJ', 'Avaliação da compra': 1, 'Tipo de pagamento': 'cartao_debito', 'Quantidade de parcelas': 1, 'Latitude': -22.25, 'Longitude': -42.66}
{'_id': ObjectId('6897d80622441912739d6c04'), 'Produto': 'Jogo de copos', 'Categoria do Produto': 'utilidades domesticas', 'Preço': 54.67, 'Frete': 9.2906273957, 'Data da Compra': '01/01/2020', 'Vendedor': 'Camila Ribeiro', 'Local da compra': 'SP', 'Avaliação da compra': 4, 'Tipo de pagamento': 'boleto', 'Quantidade de parcelas': 1, 'Latitude': -22.19, 'Longitude': -48.79}
{'_id': ObjectId('6897d80622441912739d6c05'), 'Produto': 'Lavadora de roupas', 'Categoria do Produto': 'eletrodomesticos', 'Preço': 1920.01, 'Frete': 99.8191954012, 'Data da Compra': '01/01/2020', 'Vendedor': 'Juliana Costa', 'Local da compra': 'ES', 'Avaliação da compra': 5, 'Tipo de pagamento': 'cartao_credito', 'Quantidade de parcelas': 2, 'Latitude': -19.19, 'Longitude': -40.34}
{'_id': ObjectId('6897d80622441912739d6c06'), 'Produto': 'Bola de vôlei', 'Categoria do Produto': 'esporte e lazer', 'Preço': 56.26, 'Frete': 0.0, 'Data da Compra': '01/01/2020', 'Vendedor': 'Mariana Ferreira', 'Local da compra': 'MG', 'Avaliação da compra': 3, 'Tipo de pagamento': 'cartao_credito', 'Quantidade de parcelas': 4, 'Latitude': -18.1, 'Longitude': -44.38}
{'_id': ObjectId('6897d80622441912739d6c07'), 'Produto': 'Xadrez de madeira', 'Categoria do Produto': 'brinquedos', 'Preço': 25.87, 'Frete': 1.9086041977, 'Data da Compra': '01/01/2020', 'Vendedor': 'Juliana Costa', 'Local da compra': 'SP', 'Avaliação da compra': 5, 'Tipo de pagamento': 'boleto', 'Quantidade de parcelas': 1, 'Latitude': -22.19, 'Longitude': -48.79}
{'_id': ObjectId('6897d80622441912739d6c08'), 'Produto': 'Xadrez de madeira', 'Categoria do Produto': 'brinquedos', 'Preço': 25.23, 'Frete': 0.0, 'Data da Compra': '01/01/2021', 'Vendedor': 'Thiago Silva', 'Local da compra': 'BA', 'Avaliação da compra': 5, 'Tipo de pagamento': 'cartao_credito', 'Quantidade de parcelas': 2, 'Latitude': -13.29, 'Longitude': -41.71}
{'_id': ObjectId('6897d80622441912739d6c09'), 'Produto': 'Impressora', 'Categoria do Produto': 'eletronicos', 'Preço': 322.04, 'Frete': 14.7321002401, 'Data da Compra': '01/01/2021', 'Vendedor': 'João Souza', 'Local da compra': 'SP', 'Avaliação da compra': 3, 'Tipo de pagamento': 'cartao_credito', 'Quantidade de parcelas': 1, 'Latitude': -22.19, 'Longitude': -48.79}
{'_id': ObjectId('6897d80622441912739d6c0a'), 'Produto': 'Mesa de centro', 'Categoria do Produto': 'moveis', 'Preço': 282.22, 'Frete': 12.6118050347, 'Data da Compra': '01/01/2021', 'Vendedor': 'João Souza', 'Local da compra': 'SP', 'Avaliação da compra': 3, 'Tipo de pagamento': 'boleto', 'Quantidade de parcelas': 1, 'Latitude': -22.19, 'Longitude': -48.79}
{'_id': ObjectId('6897d80622441912739d6c0b'), 'Produto': 'Tablet ABXY', 'Categoria do Produto': 'eletronicos', 'Preço': 1100.42, 'Frete': 68.4513476183, 'Data da Compra': '01/01/2021', 'Vendedor': 'Beatriz Moraes', 'Local da compra': 'SP', 'Avaliação da compra': 1, 'Tipo de pagamento': 'cupom', 'Quantidade de parcelas': 1, 'Latitude': -22.19, 'Longitude': -48.79}
{'_id': ObjectId('6897d80622441912739d6c0c'), 'Produto': 'Fogão', 'Categoria do Produto': 'eletrodomesticos', 'Preço': 791.81, 'Frete': 42.4446263246, 'Data da Compra': '01/01/2021', 'Vendedor': 'Juliana Costa', 'Local da compra': 'SP', 'Avaliação da compra': 4, 'Tipo de pagamento': 'boleto', 'Quantidade de parcelas': 1, 'Latitude': -22.19, 'Longitude': -48.79}
{'_id': ObjectId('6897d80622441912739d6c0d'), 'Produto': 'Violão', 'Categoria do Produto': 'instrumentos musicais', 'Preço': 316.84, 'Frete': 17.1595536296, 'Data da Compra': '01/01/2022', 'Vendedor': 'Pedro Gomes', 'Local da compra': 'SP', 'Avaliação da compra': 5, 'Tipo de pagamento': 'cartao_credito', 'Quantidade de parcelas': 2, 'Latitude': -22.19, 'Longitude': -48.79}
{'_id': ObjectId('6897d80622441912739d6c0e'), 'Produto': 'Geladeira', 'Categoria do Produto': 'eletrodomesticos', 'Preço': 2322.94, 'Frete': 121.2740057251, 'Data da Compra': '01/01/2022', 'Vendedor': 'Thiago Silva', 'Local da compra': 'RS', 'Avaliação da compra': 5, 'Tipo de pagamento': 'cartao_credito', 'Quantidade de parcelas': 10, 'Latitude': -30.17, 'Longitude': -53.5}
{'_id': ObjectId('6897d80622441912739d6c0f'), 'Produto': 'Secadora de roupas', 'Categoria do Produto': 'eletrodomesticos', 'Preço': 1893.04, 'Frete': 107.1782993366, 'Data da Compra': '01/01/2022', 'Vendedor': 'Beatriz Moraes', 'Local da compra': 'PR', 'Avaliação da compra': 4, 'Tipo de pagamento': 'cartao_credito', 'Quantidade de parcelas': 2, 'Latitude': -24.89, 'Longitude': -51.55}
{'_id': ObjectId('6897d80622441912739d6c10'), 'Produto': 'Jogo de copos', 'Categoria do Produto': 'utilidades domesticas', 'Preço': 37.44, 'Frete': 2.8819825404, 'Data da Compra': '01/01/2022', 'Vendedor': 'Thiago Silva', 'Local da compra': 'RJ', 'Avaliação da compra': 4, 'Tipo de pagamento': 'cartao_credito', 'Quantidade de parcelas': 4, 'Latitude': -22.25, 'Longitude': -42.66}
{'_id': ObjectId('6897d80622441912739d6c11'), 'Produto': 'Blocos de montar', 'Categoria do Produto': 'brinquedos', 'Preço': 36.84, 'Frete': 0.0, 'Data da Compra': '01/01/2022', 'Vendedor': 'Pedro Gomes', 'Local da compra': 'SP', 'Avaliação da compra': 4, 'Tipo de pagamento': 'boleto', 'Quantidade de parcelas': 1, 'Latitude': -22.19, 'Longitude': -48.79}
{'_id': ObjectId('6897d80622441912739d6c12'), 'Produto': 'Iniciando em programação', 'Categoria do Produto': 'livros', 'Preço': 63.25, 'Frete': 3.894137208, 'Data da Compra': '01/01/2022', 'Vendedor': 'Juliana Costa', 'Local da compra': 'RJ', 'Avaliação da compra': 5, 'Tipo de pagamento': 'cartao_credito', 'Quantidade de parcelas': 4, 'Latitude': -22.25, 'Longitude': -42.66}
{'_id': ObjectId('6897d80622441912739d6c13'), 'Produto': 'Fogão', 'Categoria do Produto': 'eletrodomesticos', 'Preço': 607.49, 'Frete': 33.2354300998, 'Data da Compra': '01/01/2022', 'Vendedor': 'Juliana Costa', 'Local da compra': 'MG', 'Avaliação da compra': 5, 'Tipo de pagamento': 'cartao_credito', 'Quantidade de parcelas': 3, 'Latitude': -18.1, 'Longitude': -44.38}
{'_id': ObjectId('6897d80622441912739d6c14'), 'Produto': 'Bola de vôlei', 'Categoria do Produto': 'esporte e lazer', 'Preço': 75.11, 'Frete': 1.5838206052, 'Data da Compra': '01/01/2022', 'Vendedor': 'Isabella Pereira', 'Local da compra': 'SP', 'Avaliação da compra': 5, 'Tipo de pagamento': 'cartao_credito', 'Quantidade de parcelas': 1, 'Latitude': -22.19, 'Longitude': -48.79}
{'_id': ObjectId('6897d80622441912739d6c15'), 'Produto': 'Bateria', 'Categoria do Produto': 'instrumentos musicais', 'Preço': 1031.24, 'Frete': 55.199204426, 'Data da Compra': '01/01/2023', 'Vendedor': 'Bruno Rodrigues', 'Local da compra': 'BA', 'Avaliação da compra': 5, 'Tipo de pagamento': 'boleto', 'Quantidade de parcelas': 1, 'Latitude': -13.29, 'Longitude': -41.71}
{'_id': ObjectId('6897d80622441912739d6c16'), 'Produto': 'Boneca bebê', 'Categoria do Produto': 'brinquedos', 'Preço': 50.72, 'Frete': 3.2317919389, 'Data da Compra': '01/01/2023', 'Vendedor': 'Isabella Pereira', 'Local da compra': 'SP', 'Avaliação da compra': 4, 'Tipo de pagamento': 'boleto', 'Quantidade de parcelas': 1, 'Latitude': -22.19, 'Longitude': -48.79}
{'_id': ObjectId('6897d80622441912739d6c17'), 'Produto': 'Sofá retrátil', 'Categoria do Produto': 'moveis', 'Preço': 888.09, 'Frete': 51.7681594786, 'Data da Compra': '01/01/2023', 'Vendedor': 'Rafael Costa', 'Local da compra': 'SP', 'Avaliação da compra': 4, 'Tipo de pagamento': 'cartao_credito', 'Quantidade de parcelas': 20, 'Latitude': -22.19, 'Longitude': -48.79}
{'_id': ObjectId('6897d80622441912739d6c18'), 'Produto': 'Pandeiro', 'Categoria do Produto': 'instrumentos musicais', 'Preço': 47.05, 'Frete': 2.7883968633, 'Data da Compra': '01/01/2023', 'Vendedor': 'Bianca Santos', 'Local da compra': 'RS', 'Avaliação da compra': 5, 'Tipo de pagamento': 'cartao_credito', 'Quantidade de parcelas': 6, 'Latitude': -30.17, 'Longitude': -53.5}
{'_id': ObjectId('6897d80622441912739d6c19'), 'Produto': 'Bicicleta', 'Categoria do Produto': 'esporte e lazer', 'Preço': 836.66, 'Frete': 45.438043164, 'Data da Compra': '01/01/2023', 'Vendedor': 'Larissa Alves', 'Local da compra': 'SP', 'Avaliação da compra': 5, 'Tipo de pagamento': 'cartao_credito', 'Quantidade de parcelas': 1, 'Latitude': -22.19, 'Longitude': -48.79}
{'_id': ObjectId('6897d80622441912739d6c1a'), 'Produto': 'Xadrez de madeira', 'Categoria do Produto': 'brinquedos', 'Preço': 44.82, 'Frete': 3.2749453383, 'Data da Compra': '01/01/2023', 'Vendedor': 'Bianca Santos', 'Local da compra': 'PR', 'Avaliação da compra': 5, 'Tipo de pagamento': 'cupom', 'Quantidade de parcelas': 1, 'Latitude': -24.89, 'Longitude': -51.55}
{'_id': ObjectId('6897d80622441912739d6c1b'), 'Produto': 'Lavadora de roupas', 'Categoria do Produto': 'eletrodomesticos', 'Preço': 1857.13, 'Frete': 99.169711412, 'Data da Compra': '01/02/2020', 'Vendedor': 'Bruno Rodrigues', 'Local da compra': 'RJ', 'Avaliação da compra': 5, 'Tipo de pagamento': 'boleto', 'Quantidade de parcelas': 1, 'Latitude': -22.25, 'Longitude': -42.66}
{'_id': ObjectId('6897d80622441912739d6c1c'), 'Produto': 'Mochila', 'Categoria do Produto': 'esporte e lazer', 'Preço': 123.53, 'Frete': 4.1620399383, 'Data da Compra': '01/02/2020', 'Vendedor': 'Pedro Gomes', 'Local da compra': 'RJ', 'Avaliação da compra': 5, 'Tipo de pagamento': 'cartao_credito', 'Quantidade de parcelas': 3, 'Latitude': -22.25, 'Longitude': -42.66}
{'_id': ObjectId('6897d80622441912739d6c1d'), 'Produto': 'Headset', 'Categoria do Produto': 'eletronicos', 'Preço': 309.35, 'Frete': 16.755082759, 'Data da Compra': '01/02/2020', 'Vendedor': 'Mariana Ferreira', 'Local da compra': 'RS', 'Avaliação da compra': 5, 'Tipo de pagamento': 'cartao_credito', 'Quantidade de parcelas': 3, 'Latitude': -30.17, 'Longitude': -53.5}
{'_id': ObjectId('6897d80622441912739d6c1e'), 'Produto': 'Micro-ondas', 'Categoria do Produto': 'eletrodomesticos', 'Preço': 1035.84, 'Frete': 55.6864683002, 'Data da Compra': '01/02/2021', 'Vendedor': 'Felipe Santos', 'Local da compra': 'SP', 'Avaliação da compra': 2, 'Tipo de pagamento': 'cartao_credito', 'Quantidade de parcelas': 6, 'Latitude': -22.19, 'Longitude': -48.79}
{'_id': ObjectId('6897d80622441912739d6c1f'), 'Produto': 'Cama king', 'Categoria do Produto': 'moveis', 'Preço': 660.46, 'Frete': 35.4506339784, 'Data da Compra': '01/02/2021', 'Vendedor': 'Juliana Costa', 'Local da compra': 'RJ', 'Avaliação da compra': 5, 'Tipo de pagamento': 'cartao_credito', 'Quantidade de parcelas': 3, 'Latitude': -22.25, 'Longitude': -42.66}
{'_id': ObjectId('6897d80622441912739d6c20'), 'Produto': 'Ciência de dados com python', 'Categoria do Produto': 'livros', 'Preço': 86.13, 'Frete': 5.2731755368, 'Data da Compra': '01/02/2021', 'Vendedor': 'Camila Ribeiro', 'Local da compra': 'RJ', 'Avaliação da compra': 4, 'Tipo de pagamento': 'cartao_credito', 'Quantidade de parcelas': 3, 'Latitude': -22.25, 'Longitude': -42.66}
{'_id': ObjectId('6897d80622441912739d6c21'), 'Produto': 'Guitarra', 'Categoria do Produto': 'instrumentos musicais', 'Preço': 957.84, 'Frete': 51.5283634201, 'Data da Compra': '01/02/2021', 'Vendedor': 'Isabella Pereira', 'Local da compra': 'SP', 'Avaliação da compra': 5, 'Tipo de pagamento': 'cartao_credito', 'Quantidade de parcelas': 1, 'Latitude': -22.19, 'Longitude': -48.79}
{'_id': ObjectId('6897d80622441912739d6c22'), 'Produto': 'Ciência de dados com python', 'Categoria do Produto': 'livros', 'Preço': 72.75, 'Frete': 1.458157705, 'Data da Compra': '01/02/2021', 'Vendedor': 'Beatriz Moraes', 'Local da compra': 'PR', 'Avaliação da compra': 4, 'Tipo de pagamento': 'cartao_credito', 'Quantidade de parcelas': 2, 'Latitude': -24.89, 'Longitude': -51.55}
{'_id': ObjectId('6897d80622441912739d6c23'), 'Produto': 'Cama box', 'Categoria do Produto': 'moveis', 'Preço': 819.22, 'Frete': 43.9041263642, 'Data da Compra': '01/02/2021', 'Vendedor': 'Felipe Santos', 'Local da compra': 'SP', 'Avaliação da compra': 5, 'Tipo de pagamento': 'cartao_credito', 'Quantidade de parcelas': 4, 'Latitude': -22.19, 'Longitude': -48.79}
{'_id': ObjectId('6897d80622441912739d6c24'), 'Produto': 'Headset', 'Categoria do Produto': 'eletronicos', 'Preço': 340.22, 'Frete': 15.7001305473, 'Data da Compra': '01/02/2021', 'Vendedor': 'Thiago Silva', 'Local da compra': 'SP', 'Avaliação da compra': 2, 'Tipo de pagamento': 'cupom', 'Quantidade de parcelas': 1, 'Latitude': -22.19, 'Longitude': -48.79}
{'_id': ObjectId('6897d80622441912739d6c25'), 'Produto': 'Iniciando em programação', 'Categoria do Produto': 'livros', 'Preço': 61.73, 'Frete': 0.0, 'Data da Compra': '01/02/2021', 'Vendedor': 'Beatriz Moraes', 'Local da compra': 'SP', 'Avaliação da compra': 4, 'Tipo de pagamento': 'cartao_credito', 'Quantidade de parcelas': 1, 'Latitude': -22.19, 'Longitude': -48.79}
{'_id': ObjectId('6897d80622441912739d6c26'), 'Produto': 'Jogo de panelas', 'Categoria do Produto': 'utilidades domesticas', 'Preço': 126.59, 'Frete': 4.3249757326, 'Data da Compra': '01/02/2021', 'Vendedor': 'Juliana Costa', 'Local da compra': 'RS', 'Avaliação da compra': 1, 'Tipo de pagamento': 'cartao_credito', 'Quantidade de parcelas': 3, 'Latitude': -30.17, 'Longitude': -53.5}
{'_id': ObjectId('6897d80622441912739d6c27'), 'Produto': 'Guitarra', 'Categoria do Produto': 'instrumentos musicais', 'Preço': 1158.33, 'Frete': 62.2086923009, 'Data da Compra': '01/02/2022', 'Vendedor': 'Bruno Rodrigues', 'Local da compra': 'SP', 'Avaliação da compra': 4, 'Tipo de pagamento': 'cartao_credito', 'Quantidade de parcelas': 2, 'Latitude': -22.19, 'Longitude': -48.79}
{'_id': ObjectId('6897d80622441912739d6c28'), 'Produto': 'Dashboards com Power BI', 'Categoria do Produto': 'livros', 'Preço': 57.63, 'Frete': 9.3105595123, 'Data da Compra': '01/02/2022', 'Vendedor': 'Bianca Santos', 'Local da compra': 'SP', 'Avaliação da compra': 3, 'Tipo de pagamento': 'cartao_credito', 'Quantidade de parcelas': 1, 'Latitude': -22.19, 'Longitude': -48.79}
{'_id': ObjectId('6897d80622441912739d6c29'), 'Produto': 'Copo térmico', 'Categoria do Produto': 'esporte e lazer', 'Preço': 50.31, 'Frete': 0.0, 'Data da Compra': '01/02/2022', 'Vendedor': 'Beatriz Moraes', 'Local da compra': 'RJ', 'Avaliação da compra': 1, 'Tipo de pagamento': 'cartao_credito', 'Quantidade de parcelas': 2, 'Latitude': -22.25, 'Longitude': -42.66}
{'_id': ObjectId('6897d80622441912739d6c2a'), 'Produto': 'Corda de pular', 'Categoria do Produto': 'esporte e lazer', 'Preço': 21.88, 'Frete': 0.0, 'Data da Compra': '01/02/2022', 'Vendedor': 'Larissa Alves', 'Local da compra': 'SC', 'Avaliação da compra': 5, 'Tipo de pagamento': 'cartao_credito', 'Quantidade de parcelas': 5, 'Latitude': -27.45, 'Longitude': -50.95}
{'_id': ObjectId('6897d80622441912739d6c2b'), 'Produto': 'Mesa de jantar', 'Categoria do Produto': 'moveis', 'Preço': 264.63, 'Frete': 14.6218559113, 'Data da Compra': '01/02/2022', 'Vendedor': 'Thiago Silva', 'Local da compra': 'MG', 'Avaliação da compra': 5, 'Tipo de pagamento': 'cartao_credito', 'Quantidade de parcelas': 4, 'Latitude': -18.1, 'Longitude': -44.38}
{'_id': ObjectId('6897d80622441912739d6c2c'), 'Produto': 'Ciência de dados com python', 'Categoria do Produto': 'livros', 'Preço': 79.28, 'Frete': 1.8058605601, 'Data da Compra': '01/02/2022', 'Vendedor': 'Lucas Oliveira', 'Local da compra': 'SP', 'Avaliação da compra': 5, 'Tipo de pagamento': 'cartao_credito', 'Quantidade de parcelas': 1, 'Latitude': -22.19, 'Longitude': -48.79}
{'_id': ObjectId('6897d80622441912739d6c2d'), 'Produto': 'Bicicleta', 'Categoria do Produto': 'esporte e lazer', 'Preço': 520.28, 'Frete': 27.9864706964, 'Data da Compra': '01/02/2022', 'Vendedor': 'Rafael Costa', 'Local da compra': 'SP', 'Avaliação da compra': 5, 'Tipo de pagamento': 'cartao_credito', 'Quantidade de parcelas': 5, 'Latitude': -22.19, 'Longitude': -48.79}
{'_id': ObjectId('6897d80622441912739d6c2e'), 'Produto': 'Mochila', 'Categoria do Produto': 'esporte e lazer', 'Preço': 147.99, 'Frete': 5.4644613527, 'Data da Compra': '01/02/2022', 'Vendedor': 'João Souza', 'Local da compra': 'SP', 'Avaliação da compra': 4, 'Tipo de pagamento': 'boleto', 'Quantidade de parcelas': 1, 'Latitude': -22.19, 'Longitude': -48.79}
{'_id': ObjectId('6897d80622441912739d6c2f'), 'Produto': 'Poltrona', 'Categoria do Produto': 'moveis', 'Preço': 251.37, 'Frete': 10.969135344, 'Data da Compra': '01/02/2022', 'Vendedor': 'Isabella Pereira', 'Local da compra': 'AL', 'Avaliação da compra': 4, 'Tipo de pagamento': 'boleto', 'Quantidade de parcelas': 1, 'Latitude': -9.62, 'Longitude': -36.82}
{'_id': ObjectId('6897d80622441912739d6c30'), 'Produto': 'Dashboards com Power BI', 'Categoria do Produto': 'livros', 'Preço': 41.76, 'Frete': 2.7546988942, 'Data da Compra': '01/02/2022', 'Vendedor': 'Juliana Costa', 'Local da compra': 'SP', 'Avaliação da compra': 5, 'Tipo de pagamento': 'cartao_credito', 'Quantidade de parcelas': 1, 'Latitude': -22.19, 'Longitude': -48.79}
{'_id': ObjectId('6897d80622441912739d6c31'), 'Produto': 'Ciência de dados com python', 'Categoria do Produto': 'livros', 'Preço': 82.15, 'Frete': 1.958679426, 'Data da Compra': '01/02/2023', 'Vendedor': 'Bianca Santos', 'Local da compra': 'SP', 'Avaliação da compra': 5, 'Tipo de pagamento': 'cartao_credito', 'Quantidade de parcelas': 2, 'Latitude': -22.19, 'Longitude': -48.79}
{'_id': ObjectId('6897d80622441912739d6c32'), 'Produto': 'Smartwatch', 'Categoria do Produto': 'eletronicos', 'Preço': 184.84, 'Frete': 17.9198218199, 'Data da Compra': '01/02/2023', 'Vendedor': 'Lucas Oliveira', 'Local da compra': 'BA', 'Avaliação da compra': 4, 'Tipo de pagamento': 'cartao_credito', 'Quantidade de parcelas': 3, 'Latitude': -13.29, 'Longitude': -41.71}
{'_id': ObjectId('6897d80622441912739d6c33'), 'Produto': 'Bola de vôlei', 'Categoria do Produto': 'esporte e lazer', 'Preço': 55.1, 'Frete': 3.2170351457, 'Data da Compra': '01/02/2023', 'Vendedor': 'Bianca Santos', 'Local da compra': 'SP', 'Avaliação da compra': 1, 'Tipo de pagamento': 'cartao_credito', 'Quantidade de parcelas': 4, 'Latitude': -22.19, 'Longitude': -48.79}

**Alterando os nomes dos campos de latitude e longitude**

In [4]:
collection.update_many({}, {"$rename": {"lat": "Latitude", "lon": "Longitude"}})

In [5]:
collection.find_one()

{'_id': ObjectId('6897d80622441912739d6bff'),
 'Produto': 'Modelagem preditiva',
 'Categoria do Produto': 'livros',
 'Preço': 92.45,
 'Frete': 5.6096965236,
 'Data da Compra': '01/01/2020',
 'Vendedor': 'Thiago Silva',
 'Local da compra': 'BA',
 'Avaliação da compra': 1,
 'Tipo de pagamento': 'cartao_credito',
 'Quantidade de parcelas': 3,
 'Latitude': -13.29,
 'Longitude': -41.71}

## Aplicando transformações: filtrando registros da categoria livros

Agora, vamos executar uma consulta para obter apenas os dados relacionados à categoria de **livros**.

In [6]:
collection.distinct("Categoria do Produto")

['brinquedos',
 'eletrodomesticos',
 'eletronicos',
 'esporte e lazer',
 'instrumentos musicais',
 'livros',
 'moveis',
 'utilidades domesticas']

In [7]:
query = {"Categoria do Produto": "livros"}

lista_livros = []
for doc in collection.find(query):
    #print(doc)
    lista_livros.append(doc)

In [8]:
lista_livros

[{'_id': ObjectId('6897d80622441912739d6bff'),
  'Produto': 'Modelagem preditiva',
  'Categoria do Produto': 'livros',
  'Preço': 92.45,
  'Frete': 5.6096965236,
  'Data da Compra': '01/01/2020',
  'Vendedor': 'Thiago Silva',
  'Local da compra': 'BA',
  'Avaliação da compra': 1,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 3,
  'Latitude': -13.29,
  'Longitude': -41.71},
 {'_id': ObjectId('6897d80622441912739d6c00'),
  'Produto': 'Iniciando em programação',
  'Categoria do Produto': 'livros',
  'Preço': 43.84,
  'Frete': 0.0,
  'Data da Compra': '01/01/2020',
  'Vendedor': 'Mariana Ferreira',
  'Local da compra': 'SP',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 1,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6c12'),
  'Produto': 'Iniciando em programação',
  'Categoria do Produto': 'livros',
  'Preço': 63.25,
  'Frete': 3.894137208,
  'Data da Compra': '01/01/2022',
  'Vendedor': 'Juliana Costa',
  'Local da compra': 'RJ',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 4,
  'Latitude': -22.25,
  'Longitude': -42.66},
 {'_id': ObjectId('6897d80622441912739d6c20'),
  'Produto': 'Ciência de dados com python',
  'Categoria do Produto': 'livros',
  'Preço': 86.13,
  'Frete': 5.2731755368,
  'Data da Compra': '01/02/2021',
  'Vendedor': 'Camila Ribeiro',
  'Local da compra': 'RJ',
  'Avaliação da compra': 4,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 3,
  'Latitude': -22.25,
  'Longitude': -42.66},
 {'_id': ObjectId('6897d80622441912739d6c22'),
  'Produto': 'Ciência de dados com python',
  'Categoria do Produto': 'livros',
  'Preço': 72.75,
  'Frete': 1.458157705,
  'Data da Compra': '01/02/2021',
  'Vendedor': 'Beatriz Moraes',
  'Local da compra': 'PR',
  'Avaliação da compra': 4,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 2,
  'Latitude': -24.89,
  'Longitude': -51.55},
 {'_id': ObjectId('6897d80622441912739d6c25'),
  'Produto': 'Iniciando em programação',
  'Categoria do Produto': 'livros',
  'Preço': 61.73,
  'Frete': 0.0,
  'Data da Compra': '01/02/2021',
  'Vendedor': 'Beatriz Moraes',
  'Local da compra': 'SP',
  'Avaliação da compra': 4,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 1,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6c28'),
  'Produto': 'Dashboards com Power BI',
  'Categoria do Produto': 'livros',
  'Preço': 57.63,
  'Frete': 9.3105595123,
  'Data da Compra': '01/02/2022',
  'Vendedor': 'Bianca Santos',
  'Local da compra': 'SP',
  'Avaliação da compra': 3,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 1,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6c2c'),
  'Produto': 'Ciência de dados com python',
  'Categoria do Produto': 'livros',
  'Preço': 79.28,
  'Frete': 1.8058605601,
  'Data da Compra': '01/02/2022',
  'Vendedor': 'Lucas Oliveira',
  'Local da compra': 'SP',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 1,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6c30'),
  'Produto': 'Dashboards com Power BI',
  'Categoria do Produto': 'livros',
  'Preço': 41.76,
  'Frete': 2.7546988942,
  'Data da Compra': '01/02/2022',
  'Vendedor': 'Juliana Costa',
  'Local da compra': 'SP',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 1,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6c31'),
  'Produto': 'Ciência de dados com python',
  'Categoria do Produto': 'livros',
  'Preço': 82.15,
  'Frete': 1.958679426,
  'Data da Compra': '01/02/2023',
  'Vendedor': 'Bianca Santos',
  'Local da compra': 'SP',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 2,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6c38'),
  'Produto': 'Modelagem preditiva',
  'Categoria do Produto': 'livros',
  'Preço': 70.49,
  'Frete': 1.337819504,
  'Data da Compra': '01/02/2023',
  'Vendedor': 'Isabella Pereira',
  'Local da compra': 'PE',
  'Avaliação da compra': 4,
  'Tipo de pagamento': 'cupom',
  'Quantidade de parcelas': 1,
  'Latitude': -8.38,
  'Longitude': -37.86},
 {'_id': ObjectId('6897d80622441912739d6c39'),
  'Produto': 'Dashboards com Power BI',
  'Categoria do Produto': 'livros',
  'Preço': 40.98,
  'Frete': 0.0,
  'Data da Compra': '01/02/2023',
  'Vendedor': 'Beatriz Moraes',
  'Local da compra': 'RJ',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 1,
  'Latitude': -22.25,
  'Longitude': -42.66},
 {'_id': ObjectId('6897d80622441912739d6c52'),
  'Produto': 'Ciência de dados com python',
  'Categoria do Produto': 'livros',
  'Preço': 50.51,
  'Frete': 10.2450858314,
  'Data da Compra': '01/03/2022',
  'Vendedor': 'Thiago Silva',
  'Local da compra': 'MG',
  'Avaliação da compra': 1,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 6,
  'Latitude': -18.1,
  'Longitude': -44.38},
 {'_id': ObjectId('6897d80622441912739d6c56'),
  'Produto': 'Modelagem preditiva',
  'Categoria do Produto': 'livros',
  'Preço': 71.64,
  'Frete': 1.3990535443,
  'Data da Compra': '01/03/2023',
  'Vendedor': 'Mariana Ferreira',
  'Local da compra': 'SP',
  'Avaliação da compra': 4,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 2,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6c58'),
  'Produto': 'Dashboards com Power BI',
  'Categoria do Produto': 'livros',
  'Preço': 43.35,
  'Frete': 3.2481049178,
  'Data da Compra': '01/03/2023',
  'Vendedor': 'Rafael Costa',
  'Local da compra': 'BA',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 2,
  'Latitude': -13.29,
  'Longitude': -41.71},
 {'_id': ObjectId('6897d80622441912739d6c5c'),
  'Produto': 'Iniciando em programação',
  'Categoria do Produto': 'livros',
  'Preço': 65.86,
  'Frete': 4.4466946987,
  'Data da Compra': '01/04/2020',
  'Vendedor': 'Rafael Costa',
  'Local da compra': 'SP',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 4,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6c68'),
  'Produto': 'Iniciando em programação',
  'Categoria do Produto': 'livros',
  'Preço': 83.18,
  'Frete': 5.1160969115,
  'Data da Compra': '01/04/2021',
  'Vendedor': 'Isabella Pereira',
  'Local da compra': 'SP',
  'Avaliação da compra': 3,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 4,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6c6a'),
  'Produto': 'Dashboards com Power BI',
  'Categoria do Produto': 'livros',
  'Preço': 40.85,
  'Frete': 0.0,
  'Data da Compra': '01/04/2021',
  'Vendedor': 'Mariana Ferreira',
  'Local da compra': 'SP',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 1,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6c70'),
  'Produto': 'Ciência de dados com python',
  'Categoria do Produto': 'livros',
  'Preço': 75.04,
  'Frete': 1.5800933158,
  'Data da Compra': '01/04/2022',
  'Vendedor': 'Bianca Santos',
  'Local da compra': 'RO',
  'Avaliação da compra': 2,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 7,
  'Latitude': -10.83,
  'Longitude': -63.34},
 {'_id': ObjectId('6897d80622441912739d6c7d'),
  'Produto': 'Ciência de dados com python',
  'Categoria do Produto': 'livros',
  'Preço': 58.61,
  'Frete': 4.0606540096,
  'Data da Compra': '01/05/2021',
  'Vendedor': 'Beatriz Moraes',
  'Local da compra': 'PR',
  'Avaliação da compra': 4,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 1,
  'Latitude': -24.89,
  'Longitude': -51.55},
 {'_id': ObjectId('6897d80622441912739d6c89'),
  'Produto': 'Dashboards com Power BI',
  'Categoria do Produto': 'livros',
  'Preço': 46.58,
  'Frete': 0.0,
  'Data da Compra': '01/06/2020',
  'Vendedor': 'Rafael Costa',
  'Local da compra': 'PR',
  'Avaliação da compra': 1,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 4,
  'Latitude': -24.89,
  'Longitude': -51.55},
 {'_id': ObjectId('6897d80622441912739d6c8b'),
  'Produto': 'Dashboards com Power BI',
  'Categoria do Produto': 'livros',
  'Preço': 42.09,
  'Frete': 0.0,
  'Data da Compra': '01/06/2020',
  'Vendedor': 'Felipe Santos',
  'Local da compra': 'SP',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 8,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6c90'),
  'Produto': 'Dashboards com Power BI',
  'Categoria do Produto': 'livros',
  'Preço': 55.44,
  'Frete': 3.6390253647,
  'Data da Compra': '01/06/2021',
  'Vendedor': 'Camila Ribeiro',
  'Local da compra': 'SP',
  'Avaliação da compra': 3,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 10,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6ca9'),
  'Produto': 'Dashboards com Power BI',
  'Categoria do Produto': 'livros',
  'Preço': 46.87,
  'Frete': 0.0,
  'Data da Compra': '01/07/2021',
  'Vendedor': 'Beatriz Moraes',
  'Local da compra': 'RS',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 8,
  'Latitude': -30.17,
  'Longitude': -53.5},
 {'_id': ObjectId('6897d80622441912739d6cb2'),
  'Produto': 'Iniciando em programação',
  'Categoria do Produto': 'livros',
  'Preço': 56.9,
  'Frete': 3.560858347,
  'Data da Compra': '01/07/2021',
  'Vendedor': 'Mariana Ferreira',
  'Local da compra': 'SP',
  'Avaliação da compra': 4,
  'Tipo de pagamento': 'boleto',
  'Quantidade de parcelas': 1,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6cbb'),
  'Produto': 'Modelagem preditiva',
  'Categoria do Produto': 'livros',
  'Preço': 105.99,
  'Frete': 3.2280877057,
  'Data da Compra': '01/07/2022',
  'Vendedor': 'Thiago Silva',
  'Local da compra': 'SP',
  'Avaliação da compra': 1,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 4,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6cc3'),
  'Produto': 'Iniciando em programação',
  'Categoria do Produto': 'livros',
  'Preço': 55.86,
  'Frete': 6.1381932733,
  'Data da Compra': '01/08/2020',
  'Vendedor': 'Pedro Gomes',
  'Local da compra': 'CE',
  'Avaliação da compra': 3,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 9,
  'Latitude': -5.2,
  'Longitude': -39.53},
 {'_id': ObjectId('6897d80622441912739d6cd0'),
  'Produto': 'Modelagem preditiva',
  'Categoria do Produto': 'livros',
  'Preço': 101.54,
  'Frete': 14.5010858917,
  'Data da Compra': '01/08/2021',
  'Vendedor': 'Rafael Costa',
  'Local da compra': 'DF',
  'Avaliação da compra': 3,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 4,
  'Latitude': -15.83,
  'Longitude': -47.86},
 {'_id': ObjectId('6897d80622441912739d6cd5'),
  'Produto': 'Iniciando em programação',
  'Categoria do Produto': 'livros',
  'Preço': 41.11,
  'Frete': 0.0,
  'Data da Compra': '01/08/2022',
  'Vendedor': 'Thiago Silva',
  'Local da compra': 'ES',
  'Avaliação da compra': 1,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 1,
  'Latitude': -19.19,
  'Longitude': -40.34},
 {'_id': ObjectId('6897d80622441912739d6d02'),
  'Produto': 'Ciência de dados com python',
  'Categoria do Produto': 'livros',
  'Preço': 80.32,
  'Frete': 1.8612374314,
  'Data da Compra': '01/10/2021',
  'Vendedor': 'Rafael Costa',
  'Local da compra': 'SP',
  'Avaliação da compra': 4,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 2,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6d0e'),
  'Produto': 'Ciência de dados com python',
  'Categoria do Produto': 'livros',
  'Preço': 88.2,
  'Frete': 4.9795105675,
  'Data da Compra': '01/10/2022',
  'Vendedor': 'Rafael Costa',
  'Local da compra': 'SP',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 4,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6d10'),
  'Produto': 'Dashboards com Power BI',
  'Categoria do Produto': 'livros',
  'Preço': 54.59,
  'Frete': 3.18987918,
  'Data da Compra': '01/10/2022',
  'Vendedor': 'Juliana Costa',
  'Local da compra': 'SP',
  'Avaliação da compra': 3,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 8,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6d13'),
  'Produto': 'Iniciando em programação',
  'Categoria do Produto': 'livros',
  'Preço': 64.22,
  'Frete': 4.3079369753,
  'Data da Compra': '01/11/2020',
  'Vendedor': 'Thiago Silva',
  'Local da compra': 'CE',
  'Avaliação da compra': 1,
  'Tipo de pagamento': 'boleto',
  'Quantidade de parcelas': 1,
  'Latitude': -5.2,
  'Longitude': -39.53},
 {'_id': ObjectId('6897d80622441912739d6d16'),
  'Produto': 'Iniciando em programação',
  'Categoria do Produto': 'livros',
  'Preço': 40.74,
  'Frete': 0.0,
  'Data da Compra': '01/11/2020',
  'Vendedor': 'Felipe Santos',
  'Local da compra': 'SP',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 8,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6d17'),
  'Produto': 'Iniciando em programação',
  'Categoria do Produto': 'livros',
  'Preço': 46.79,
  'Frete': 0.0,
  'Data da Compra': '01/11/2020',
  'Vendedor': 'Rafael Costa',
  'Local da compra': 'SP',
  'Avaliação da compra': 4,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 2,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6d19'),
  'Produto': 'Iniciando em programação',
  'Categoria do Produto': 'livros',
  'Preço': 60.27,
  'Frete': 3.4923220922,
  'Data da Compra': '01/11/2021',
  'Vendedor': 'Juliana Costa',
  'Local da compra': 'SP',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 1,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6d1e'),
  'Produto': 'Iniciando em programação',
  'Categoria do Produto': 'livros',
  'Preço': 70.05,
  'Frete': 6.8937680841,
  'Data da Compra': '01/11/2022',
  'Vendedor': 'Pedro Gomes',
  'Local da compra': 'SP',
  'Avaliação da compra': 4,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 1,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6d22'),
  'Produto': 'Dashboards com Power BI',
  'Categoria do Produto': 'livros',
  'Preço': 51.67,
  'Frete': 3.0343979645,
  'Data da Compra': '01/11/2022',
  'Vendedor': 'Larissa Alves',
  'Local da compra': 'SP',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 1,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6d2f'),
  'Produto': 'Ciência de dados com python',
  'Categoria do Produto': 'livros',
  'Preço': 94.87,
  'Frete': 5.5826466179,
  'Data da Compra': '01/12/2021',
  'Vendedor': 'Isabella Pereira',
  'Local da compra': 'CE',
  'Avaliação da compra': 1,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 7,
  'Latitude': -5.2,
  'Longitude': -39.53},
 {'_id': ObjectId('6897d80622441912739d6d3b'),
  'Produto': 'Modelagem preditiva',
  'Categoria do Produto': 'livros',
  'Preço': 79.82,
  'Frete': 1.8346139356,
  'Data da Compra': '01/12/2022',
  'Vendedor': 'Felipe Santos',
  'Local da compra': 'CE',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 1,
  'Latitude': -5.2,
  'Longitude': -39.53},
 {'_id': ObjectId('6897d80622441912739d6d48'),
  'Produto': 'Dashboards com Power BI',
  'Categoria do Produto': 'livros',
  'Preço': 49.69,
  'Frete': 10.4438941213,
  'Data da Compra': '02/01/2020',
  'Vendedor': 'Bruno Rodrigues',
  'Local da compra': 'SP',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 1,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6d5b'),
  'Produto': 'Modelagem preditiva',
  'Categoria do Produto': 'livros',
  'Preço': 95.7,
  'Frete': 9.5757758076,
  'Data da Compra': '02/01/2022',
  'Vendedor': 'Juliana Costa',
  'Local da compra': 'SP',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 1,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6d62'),
  'Produto': 'Dashboards com Power BI',
  'Categoria do Produto': 'livros',
  'Preço': 52.47,
  'Frete': 3.0826464613,
  'Data da Compra': '02/01/2023',
  'Vendedor': 'Felipe Santos',
  'Local da compra': 'MG',
  'Avaliação da compra': 3,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 6,
  'Latitude': -18.1,
  'Longitude': -44.38},
 {'_id': ObjectId('6897d80622441912739d6d7e'),
  'Produto': 'Modelagem preditiva',
  'Categoria do Produto': 'livros',
  'Preço': 64.69,
  'Frete': 3.7276737951,
  'Data da Compra': '02/02/2022',
  'Vendedor': 'Larissa Alves',
  'Local da compra': 'SP',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 2,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6da5'),
  'Produto': 'Iniciando em programação',
  'Categoria do Produto': 'livros',
  'Preço': 88.6,
  'Frete': 5.6060986304,
  'Data da Compra': '02/03/2023',
  'Vendedor': 'Isabella Pereira',
  'Local da compra': 'SP',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 1,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6da6'),
  'Produto': 'Modelagem preditiva',
  'Categoria do Produto': 'livros',
  'Preço': 84.08,
  'Frete': 2.0614461198,
  'Data da Compra': '02/03/2023',
  'Vendedor': 'Lucas Oliveira',
  'Local da compra': 'SC',
  'Avaliação da compra': 1,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 1,
  'Latitude': -27.45,
  'Longitude': -50.95},
 {'_id': ObjectId('6897d80622441912739d6da7'),
  'Produto': 'Ciência de dados com python',
  'Categoria do Produto': 'livros',
  'Preço': 72.73,
  'Frete': 1.4570927652,
  'Data da Compra': '02/03/2023',
  'Vendedor': 'Rafael Costa',
  'Local da compra': 'PR',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 2,
  'Latitude': -24.89,
  'Longitude': -51.55},
 {'_id': ObjectId('6897d80622441912739d6db4'),
  'Produto': 'Modelagem preditiva',
  'Categoria do Produto': 'livros',
  'Preço': 61.12,
  'Frete': 3.7855606515,
  'Data da Compra': '02/04/2021',
  'Vendedor': 'Isabella Pereira',
  'Local da compra': 'BA',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 10,
  'Latitude': -13.29,
  'Longitude': -41.71},
 {'_id': ObjectId('6897d80622441912739d6dc8'),
  'Produto': 'Iniciando em programação',
  'Categoria do Produto': 'livros',
  'Preço': 88.14,
  'Frete': 2.2776289057,
  'Data da Compra': '02/05/2021',
  'Vendedor': 'Rafael Costa',
  'Local da compra': 'SP',
  'Avaliação da compra': 1,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 1,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6dca'),
  'Produto': 'Dashboards com Power BI',
  'Categoria do Produto': 'livros',
  'Preço': 47.26,
  'Frete': 0.0,
  'Data da Compra': '02/05/2021',
  'Vendedor': 'Isabella Pereira',
  'Local da compra': 'RJ',
  'Avaliação da compra': 2,

**Salvando os dados em um DataFrame**

In [9]:
import pandas as pd

df_livros = pd.DataFrame(lista_livros)
df_livros.head()

,_id,Produto,Categoria do Produto,Preço,Frete,Data da Compra,Vendedor,Local da compra,Avaliação da compra,Tipo de pagamento,Quantidade de parcelas,Latitude,Longitude
0,6897d80622441912739d6bff,Modelagem preditiva,livros,92.45,5.609697,01/01/2020,Thiago Silva,BA,1,cartao_credito,3,-13.29,-41.71
1,6897d80622441912739d6c00,Iniciando em programação,livros,43.84,0.000000,01/01/2020,Mariana Ferreira,SP,5,cartao_credito,1,-22.19,-48.79
2,6897d80622441912739d6c12,Iniciando em programação,livros,63.25,3.894137,01/01/2022,Juliana Costa,RJ,5,cartao_credito,4,-22.25,-42.66
3,6897d80622441912739d6c20,Ciência de dados com python,livros,86.13,5.273176,01/02/2021,Camila Ribeiro,RJ,4,cartao_credito,3,-22.25,-42.66
4,6897d80622441912739d6c22,Ciência de dados com python,livros,72.75,1.458158,01/02/2021,Beatriz Moraes,PR,4,cartao_credito,2,-24.89,-51.55

## Formatando as datas

Para adicionar dados do tipo DATE em um banco de dados MySQL, é necessário que a data esteja no formato **%Y-%m-%d (ano-mês-dia)**. Portanto, realizaremos uma transformação na coluna "Data de Compra" para ajustá-la a esse formato. Dessa forma, poderemos armazenar corretamente as datas no banco de dados MySQL, garantindo consistência e facilitando consultas baseadas em datas posteriormente.

In [10]:
df_livros.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1484 entries, 0 to 1483
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   _id                     1484 non-null   object
 1   Produto                 1484 non-null   object
 2   Categoria do Produto    1484 non-null   object
 3   Preço                   1484 non-null   float64
 4   Frete                   1484 non-null   float64
 5   Data da Compra          1484 non-null   object
 6   Vendedor                1484 non-null   object
 7   Local da compra         1484 non-null   object
 8   Avaliação da compra     1484 non-null   int64
 9   Tipo de pagamento       1484 non-null   object
 10  Quantidade de parcelas  1484 non-null   int64
 11  Latitude                1484 non-null   float64
 12  Longitude               1484 non-null   float64
dtypes: float64(4), int64(2), object(7)
memory usage: 150.8+ KB

In [11]:
df_livros["Data da Compra"] = pd.to_datetime(df_livros["Data da Compra"], format="%d/%m/%Y")
df_livros.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1484 entries, 0 to 1483
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   _id                     1484 non-null   object
 1   Produto                 1484 non-null   object
 2   Categoria do Produto    1484 non-null   object
 3   Preço                   1484 non-null   float64
 4   Frete                   1484 non-null   float64
 5   Data da Compra          1484 non-null   datetime64[ns]
 6   Vendedor                1484 non-null   object
 7   Local da compra         1484 non-null   object
 8   Avaliação da compra     1484 non-null   int64
 9   Tipo de pagamento       1484 non-null   object
 10  Quantidade de parcelas  1484 non-null   int64
 11  Latitude                1484 non-null   float64
 12  Longitude               1484 non-null   float64
dtypes: datetime64[ns](1), float64(4), int64(2), object(6)
memory usage: 150.8+ KB

In [12]:
df_livros["Data da Compra"] = df_livros["Data da Compra"].dt.strftime("%Y-%m-%d")
df_livros.head()

,_id,Produto,Categoria do Produto,Preço,Frete,Data da Compra,Vendedor,Local da compra,Avaliação da compra,Tipo de pagamento,Quantidade de parcelas,Latitude,Longitude
0,6897d80622441912739d6bff,Modelagem preditiva,livros,92.45,5.609697,2020-01-01,Thiago Silva,BA,1,cartao_credito,3,-13.29,-41.71
1,6897d80622441912739d6c00,Iniciando em programação,livros,43.84,0.000000,2020-01-01,Mariana Ferreira,SP,5,cartao_credito,1,-22.19,-48.79
2,6897d80622441912739d6c12,Iniciando em programação,livros,63.25,3.894137,2022-01-01,Juliana Costa,RJ,5,cartao_credito,4,-22.25,-42.66
3,6897d80622441912739d6c20,Ciência de dados com python,livros,86.13,5.273176,2021-02-01,Camila Ribeiro,RJ,4,cartao_credito,3,-22.25,-42.66
4,6897d80622441912739d6c22,Ciência de dados com python,livros,72.75,1.458158,2021-02-01,Beatriz Moraes,PR,4,cartao_credito,2,-24.89,-51.55

In [13]:
df_livros.to_csv("../data/tabela_livros.csv", index=False)

## Aplicando transformações: filtrando produtos vendidos a partir de 2021

Nesta etapa, faremos uma query para selecionar apenas os produtos vendidos a partir do ano de 2021. Utilizaremos um filtro na coluna de data de compra para obter os registros que atendam a essa condição.

In [14]:
collection.find_one()

{'_id': ObjectId('6897d80622441912739d6bff'),
 'Produto': 'Modelagem preditiva',
 'Categoria do Produto': 'livros',
 'Preço': 92.45,
 'Frete': 5.6096965236,
 'Data da Compra': '01/01/2020',
 'Vendedor': 'Thiago Silva',
 'Local da compra': 'BA',
 'Avaliação da compra': 1,
 'Tipo de pagamento': 'cartao_credito',
 'Quantidade de parcelas': 3,
 'Latitude': -13.29,
 'Longitude': -41.71}

In [15]:
query = {"Data da Compra": {"$regex": "/202[1-9]"}}

lista_produtos = []
for doc in collection.find(query):
    lista_produtos.append(doc)

In [16]:
lista_produtos

[{'_id': ObjectId('6897d80622441912739d6c08'),
  'Produto': 'Xadrez de madeira',
  'Categoria do Produto': 'brinquedos',
  'Preço': 25.23,
  'Frete': 0.0,
  'Data da Compra': '01/01/2021',
  'Vendedor': 'Thiago Silva',
  'Local da compra': 'BA',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 2,
  'Latitude': -13.29,
  'Longitude': -41.71},
 {'_id': ObjectId('6897d80622441912739d6c09'),
  'Produto': 'Impressora',
  'Categoria do Produto': 'eletronicos',
  'Preço': 322.04,
  'Frete': 14.7321002401,
  'Data da Compra': '01/01/2021',
  'Vendedor': 'João Souza',
  'Local da compra': 'SP',
  'Avaliação da compra': 3,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 1,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6c0a'),
  'Produto': 'Mesa de centro',
  'Categoria do Produto': 'moveis',
  'Preço': 282.22,
  'Frete': 12.6118050347,
  'Data da Compra': '01/01/2021',
  'Vendedor': 'João Souza',
  'Local da compra': 'SP',
  'Avaliação da compra': 3,
  'Tipo de pagamento': 'boleto',
  'Quantidade de parcelas': 1,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6c0b'),
  'Produto': 'Tablet ABXY',
  'Categoria do Produto': 'eletronicos',
  'Preço': 1100.42,
  'Frete': 68.4513476183,
  'Data da Compra': '01/01/2021',
  'Vendedor': 'Beatriz Moraes',
  'Local da compra': 'SP',
  'Avaliação da compra': 1,
  'Tipo de pagamento': 'cupom',
  'Quantidade de parcelas': 1,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6c0c'),
  'Produto': 'Fogão',
  'Categoria do Produto': 'eletrodomesticos',
  'Preço': 791.81,
  'Frete': 42.4446263246,
  'Data da Compra': '01/01/2021',
  'Vendedor': 'Juliana Costa',
  'Local da compra': 'SP',
  'Avaliação da compra': 4,
  'Tipo de pagamento': 'boleto',
  'Quantidade de parcelas': 1,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6c0d'),
  'Produto': 'Violão',
  'Categoria do Produto': 'instrumentos musicais',
  'Preço': 316.84,
  'Frete': 17.1595536296,
  'Data da Compra': '01/01/2022',
  'Vendedor': 'Pedro Gomes',
  'Local da compra': 'SP',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 2,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6c0e'),
  'Produto': 'Geladeira',
  'Categoria do Produto': 'eletrodomesticos',
  'Preço': 2322.94,
  'Frete': 121.2740057251,
  'Data da Compra': '01/01/2022',
  'Vendedor': 'Thiago Silva',
  'Local da compra': 'RS',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 10,
  'Latitude': -30.17,
  'Longitude': -53.5},
 {'_id': ObjectId('6897d80622441912739d6c0f'),
  'Produto': 'Secadora de roupas',
  'Categoria do Produto': 'eletrodomesticos',
  'Preço': 1893.04,
  'Frete': 107.1782993366,
  'Data da Compra': '01/01/2022',
  'Vendedor': 'Beatriz Moraes',
  'Local da compra': 'PR',
  'Avaliação da compra': 4,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 2,
  'Latitude': -24.89,
  'Longitude': -51.55},
 {'_id': ObjectId('6897d80622441912739d6c10'),
  'Produto': 'Jogo de copos',
  'Categoria do Produto': 'utilidades domesticas',
  'Preço': 37.44,
  'Frete': 2.8819825404,
  'Data da Compra': '01/01/2022',
  'Vendedor': 'Thiago Silva',
  'Local da compra': 'RJ',
  'Avaliação da compra': 4,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 4,
  'Latitude': -22.25,
  'Longitude': -42.66},
 {'_id': ObjectId('6897d80622441912739d6c11'),
  'Produto': 'Blocos de montar',
  'Categoria do Produto': 'brinquedos',
  'Preço': 36.84,
  'Frete': 0.0,
  'Data da Compra': '01/01/2022',
  'Vendedor': 'Pedro Gomes',
  'Local da compra': 'SP',
  'Avaliação da compra': 4,
  'Tipo de pagamento': 'boleto',
  'Quantidade de parcelas': 1,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6c12'),
  'Produto': 'Iniciando em programação',
  'Categoria do Produto': 'livros',
  'Preço': 63.25,
  'Frete': 3.894137208,
  'Data da Compra': '01/01/2022',
  'Vendedor': 'Juliana Costa',
  'Local da compra': 'RJ',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 4,
  'Latitude': -22.25,
  'Longitude': -42.66},
 {'_id': ObjectId('6897d80622441912739d6c13'),
  'Produto': 'Fogão',
  'Categoria do Produto': 'eletrodomesticos',
  'Preço': 607.49,
  'Frete': 33.2354300998,
  'Data da Compra': '01/01/2022',
  'Vendedor': 'Juliana Costa',
  'Local da compra': 'MG',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 3,
  'Latitude': -18.1,
  'Longitude': -44.38},
 {'_id': ObjectId('6897d80622441912739d6c14'),
  'Produto': 'Bola de vôlei',
  'Categoria do Produto': 'esporte e lazer',
  'Preço': 75.11,
  'Frete': 1.5838206052,
  'Data da Compra': '01/01/2022',
  'Vendedor': 'Isabella Pereira',
  'Local da compra': 'SP',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 1,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6c15'),
  'Produto': 'Bateria',
  'Categoria do Produto': 'instrumentos musicais',
  'Preço': 1031.24,
  'Frete': 55.199204426,
  'Data da Compra': '01/01/2023',
  'Vendedor': 'Bruno Rodrigues',
  'Local da compra': 'BA',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'boleto',
  'Quantidade de parcelas': 1,
  'Latitude': -13.29,
  'Longitude': -41.71},
 {'_id': ObjectId('6897d80622441912739d6c16'),
  'Produto': 'Boneca bebê',
  'Categoria do Produto': 'brinquedos',
  'Preço': 50.72,
  'Frete': 3.2317919389,
  'Data da Compra': '01/01/2023',
  'Vendedor': 'Isabella Pereira',
  'Local da compra': 'SP',
  'Avaliação da compra': 4,
  'Tipo de pagamento': 'boleto',
  'Quantidade de parcelas': 1,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6c17'),
  'Produto': 'Sofá retrátil',
  'Categoria do Produto': 'moveis',
  'Preço': 888.09,
  'Frete': 51.7681594786,
  'Data da Compra': '01/01/2023',
  'Vendedor': 'Rafael Costa',
  'Local da compra': 'SP',
  'Avaliação da compra': 4,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 20,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6c18'),
  'Produto': 'Pandeiro',
  'Categoria do Produto': 'instrumentos musicais',
  'Preço': 47.05,
  'Frete': 2.7883968633,
  'Data da Compra': '01/01/2023',
  'Vendedor': 'Bianca Santos',
  'Local da compra': 'RS',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 6,
  'Latitude': -30.17,
  'Longitude': -53.5},
 {'_id': ObjectId('6897d80622441912739d6c19'),
  'Produto': 'Bicicleta',
  'Categoria do Produto': 'esporte e lazer',
  'Preço': 836.66,
  'Frete': 45.438043164,
  'Data da Compra': '01/01/2023',
  'Vendedor': 'Larissa Alves',
  'Local da compra': 'SP',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 1,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6c1a'),
  'Produto': 'Xadrez de madeira',
  'Categoria do Produto': 'brinquedos',
  'Preço': 44.82,
  'Frete': 3.2749453383,
  'Data da Compra': '01/01/2023',
  'Vendedor': 'Bianca Santos',
  'Local da compra': 'PR',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cupom',
  'Quantidade de parcelas': 1,
  'Latitude': -24.89,
  'Longitude': -51.55},
 {'_id': ObjectId('6897d80622441912739d6c1e'),
  'Produto': 'Micro-ondas',
  'Categoria do Produto': 'eletrodomesticos',
  'Preço': 1035.84,
  'Frete': 55.6864683002,
  'Data da Compra': '01/02/2021',
  'Vendedor': 'Felipe Santos',
  'Local da compra': 'SP',
  'Avaliação da compra': 2,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 6,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6c1f'),
  'Produto': 'Cama king',
  'Categoria do Produto': 'moveis',
  'Preço': 660.46,
  'Frete': 35.4506339784,
  'Data da Compra': '01/02/2021',
  'Vendedor': 'Juliana Costa',
  'Local da compra': 'RJ',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 3,
  'Latitude': -22.25,
  'Longitude': -42.66},
 {'_id': ObjectId('6897d80622441912739d6c20'),
  'Produto': 'Ciência de dados com python',
  'Categoria do Produto': 'livros',
  'Preço': 86.13,
  'Frete': 5.2731755368,
  'Data da Compra': '01/02/2021',
  'Vendedor': 'Camila Ribeiro',
  'Local da compra': 'RJ',
  'Avaliação da compra': 4,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 3,
  'Latitude': -22.25,
  'Longitude': -42.66},
 {'_id': ObjectId('6897d80622441912739d6c21'),
  'Produto': 'Guitarra',
  'Categoria do Produto': 'instrumentos musicais',
  'Preço': 957.84,
  'Frete': 51.5283634201,
  'Data da Compra': '01/02/2021',
  'Vendedor': 'Isabella Pereira',
  'Local da compra': 'SP',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 1,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6c22'),
  'Produto': 'Ciência de dados com python',
  'Categoria do Produto': 'livros',
  'Preço': 72.75,
  'Frete': 1.458157705,
  'Data da Compra': '01/02/2021',
  'Vendedor': 'Beatriz Moraes',
  'Local da compra': 'PR',
  'Avaliação da compra': 4,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 2,
  'Latitude': -24.89,
  'Longitude': -51.55},
 {'_id': ObjectId('6897d80622441912739d6c23'),
  'Produto': 'Cama box',
  'Categoria do Produto': 'moveis',
  'Preço': 819.22,
  'Frete': 43.9041263642,
  'Data da Compra': '01/02/2021',
  'Vendedor': 'Felipe Santos',
  'Local da compra': 'SP',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 4,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6c24'),
  'Produto': 'Headset',
  'Categoria do Produto': 'eletronicos',
  'Preço': 340.22,
  'Frete': 15.7001305473,
  'Data da Compra': '01/02/2021',
  'Vendedor': 'Thiago Silva',
  'Local da compra': 'SP',
  'Avaliação da compra': 2,
  'Tipo de pagamento': 'cupom',
  'Quantidade de parcelas': 1,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6c25'),
  'Produto': 'Iniciando em programação',
  'Categoria do Produto': 'livros',
  'Preço': 61.73,
  'Frete': 0.0,
  'Data da Compra': '01/02/2021',
  'Vendedor': 'Beatriz Moraes',
  'Local da compra': 'SP',
  'Avaliação da compra': 4,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 1,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6c26'),
  'Produto': 'Jogo de panelas',
  'Categoria do Produto': 'utilidades domesticas',
  'Preço': 126.59,
  'Frete': 4.3249757326,
  'Data da Compra': '01/02/2021',
  'Vendedor': 'Juliana Costa',
  'Local da compra': 'RS',
  'Avaliação da compra': 1,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 3,
  'Latitude': -30.17,
  'Longitude': -53.5},
 {'_id': ObjectId('6897d80622441912739d6c27'),
  'Produto': 'Guitarra',
  'Categoria do Produto': 'instrumentos musicais',
  'Preço': 1158.33,
  'Frete': 62.2086923009,
  'Data da Compra': '01/02/2022',
  'Vendedor': 'Bruno Rodrigues',
  'Local da compra': 'SP',
  'Avaliação da compra': 4,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 2,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6c28'),
  'Produto': 'Dashboards com Power BI',
  'Categoria do Produto': 'livros',
  'Preço': 57.63,
  'Frete': 9.3105595123,
  'Data da Compra': '01/02/2022',
  'Vendedor': 'Bianca Santos',
  'Local da compra': 'SP',
  'Avaliação da compra': 3,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 1,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6c29'),
  'Produto': 'Copo térmico',
  'Categoria do Produto': 'esporte e lazer',
  'Preço': 50.31,
  'Frete': 0.0,
  'Data da Compra': '01/02/2022',
  'Vendedor': 'Beatriz Moraes',
  'Local da compra': 'RJ',
  'Avaliação da compra': 1,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 2,
  'Latitude': -22.25,
  'Longitude': -42.66},
 {'_id': ObjectId('6897d80622441912739d6c2a'),
  'Produto': 'Corda de pular',
  'Categoria do Produto': 'esporte e lazer',
  'Preço': 21.88,
  'Frete': 0.0,
  'Data da Compra': '01/02/2022',
  'Vendedor': 'Larissa Alves',
  'Local da compra': 'SC',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 5,
  'Latitude': -27.45,
  'Longitude': -50.95},
 {'_id': ObjectId('6897d80622441912739d6c2b'),
  'Produto': 'Mesa de jantar',
  'Categoria do Produto': 'moveis',
  'Preço': 264.63,
  'Frete': 14.6218559113,
  'Data da Compra': '01/02/2022',
  'Vendedor': 'Thiago Silva',
  'Local da compra': 'MG',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 4,
  'Latitude': -18.1,
  'Longitude': -44.38},
 {'_id': ObjectId('6897d80622441912739d6c2c'),
  'Produto': 'Ciência de dados com python',
  'Categoria do Produto': 'livros',
  'Preço': 79.28,
  'Frete': 1.8058605601,
  'Data da Compra': '01/02/2022',
  'Vendedor': 'Lucas Oliveira',
  'Local da compra': 'SP',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 1,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6c2d'),
  'Produto': 'Bicicleta',
  'Categoria do Produto': 'esporte e lazer',
  'Preço': 520.28,
  'Frete': 27.9864706964,
  'Data da Compra': '01/02/2022',
  'Vendedor': 'Rafael Costa',
  'Local da compra': 'SP',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 5,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6c2e'),
  'Produto': 'Mochila',
  'Categoria do Produto': 'esporte e lazer',
  'Preço': 147.99,
  'Frete': 5.4644613527,
  'Data da Compra': '01/02/2022',
  'Vendedor': 'João Souza',
  'Local da compra': 'SP',
  'Avaliação da compra': 4,
  'Tipo de pagamento': 'boleto',
  'Quantidade de parcelas': 1,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6c2f'),
  'Produto': 'Poltrona',
  'Categoria do Produto': 'moveis',
  'Preço': 251.37,
  'Frete': 10.969135344,
  'Data da Compra': '01/02/2022',
  'Vendedor': 'Isabella Pereira',
  'Local da compra': 'AL',
  'Avaliação da compra': 4,
  'Tipo de pagamento': 'boleto',
  'Quantidade de parcelas': 1,
  'Latitude': -9.62,
  'Longitude': -36.82},
 {'_id': ObjectId('6897d80622441912739d6c30'),
  'Produto': 'Dashboards com Power BI',
  'Categoria do Produto': 'livros',
  'Preço': 41.76,
  'Frete': 2.7546988942,
  'Data da Compra': '01/02/2022',
  'Vendedor': 'Juliana Costa',
  'Local da compra': 'SP',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 1,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6c31'),
  'Produto': 'Ciência de dados com python',
  'Categoria do Produto': 'livros',
  'Preço': 82.15,
  'Frete': 1.958679426,
  'Data da Compra': '01/02/2023',
  'Vendedor': 'Bianca Santos',
  'Local da compra': 'SP',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 2,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6c32'),
  'Produto': 'Smartwatch',
  'Categoria do Produto': 'eletronicos',
  'Preço': 184.84,
  'Frete': 17.9198218199,
  'Data da Compra': '01/02/2023',
  'Vendedor': 'Lucas Oliveira',
  'Local da compra': 'BA',
  'Avaliação da compra': 4,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 3,
  'Latitude': -13.29,
  'Longitude': -41.71},
 {'_id': ObjectId('6897d80622441912739d6c33'),
  'Produto': 'Bola de vôlei',
  'Categoria do Produto': 'esporte e lazer',
  'Preço': 55.1,
  'Frete': 3.2170351457,
  'Data da Compra': '01/02/2023',
  'Vendedor': 'Bianca Santos',
  'Local da compra': 'SP',
  'Avaliação da compra': 1,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 4,
  'Latitude': -22.19,
  'Longitude': -48.79},
 {'_id': ObjectId('6897d80622441912739d6c34'),
  'Produto': 'Cômoda',
  'Categoria do Produto': 'moveis',
  'Preço': 417.02,
  'Frete': 19.7894995019,
  'Data da Compra': '01/02/2023',
  'Vendedor': 'Felipe Santos',
  'Local da compra': 'PR',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 2,
  'Latitude': -24.89,
  'Longitude': -51.55},
 {'_id': ObjectId('6897d80622441912739d6c35'),
  'Produto': 'Fone de ouvido',
  'Categoria do Produto': 'eletronicos',
  'Preço': 108.12,
  'Frete': 6.6969125635,
  'Data da Compra': '01/02/2023',
  'Vendedor': 'Beatriz Moraes',
  'Local da compra': 'PR',
  'Avaliação da compra': 4,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 5,
  'Latitude': -24.89,
  'Longitude': -51.55},
 {'_id': ObjectId('6897d80622441912739d6c36'),
  'Produto': 'Lava louças',
  'Categoria do Produto': 'eletrodomesticos',
  'Preço': 1702.95,
  'Frete': 88.2614034053,
  'Data da Compra': '01/02/2023',
  'Vendedor': 'João Souza',
  'Local da compra': 'PR',
  'Avaliação da compra': 2,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 10,
  'Latitude': -24.89,
  'Longitude': -51.55},
 {'_id': ObjectId('6897d80622441912739d6c37'),
  'Produto': 'TV Led UHD 4K',
  'Categoria do Produto': 'eletronicos',
  'Preço': 2404.01,
  'Frete': 125.5907393338,
  'Data da Compra': '01/02/2023',
  'Vendedor': 'Pedro Gomes',
  'Local da compra': 'MG',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 2,
  'Latitude': -18.1,
  'Longitude': -44.38},
 {'_id': ObjectId('6897d80622441912739d6c38'),
  'Produto': 'Modelagem preditiva',
  'Categoria do Produto': 'livros',
  'Preço': 70.49,
  'Frete': 1.337819504,
  'Data da Compra': '01/02/2023',
  'Vendedor': 'Isabella Pereira',
  'Local da compra': 'PE',
  'Avaliação da compra': 4,
  'Tipo de pagamento': 'cupom',
  'Quantidade de parcelas': 1,
  'Latitude': -8.38,
  'Longitude': -37.86},
 {'_id': ObjectId('6897d80622441912739d6c39'),
  'Produto': 'Dashboards com Power BI',
  'Categoria do Produto': 'livros',
  'Preço': 40.98,
  'Frete': 0.0,
  'Data da Compra': '01/02/2023',
  'Vendedor': 'Beatriz Moraes',
  'Local da compra': 'RJ',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 1,
  'Latitude': -22.25,
  'Longitude': -42.66},
 {'_id': ObjectId('6897d80622441912739d6c3a'),
  'Produto': 'Assistente virtual',
  'Categoria do Produto': 'eletronicos',
  'Preço': 214.5,
  'Frete': 9.0059187638,
  'Data da Compra': '01/02/2023',
  'Vendedor': 'Thiago Silva',
  'Local da compra': 'BA',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 10,
  'Latitude': -13.29,
  'Longitude': -41.71},
 {'_id': ObjectId('6897d80622441912739d6c43'),
  'Produto': 'Geladeira',
  'Categoria do Produto': 'eletrodomesticos',
  'Preço': 2774.0,
  'Frete': 147.9902805969,
  'Data da Compra': '01/03/2021',
  'Vendedor': 'Bruno Rodrigues',
  'Local da compra': 'RJ',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 1,
  'Latitude': -22.25,
  'Longitude': -42.66},
 {'_id': ObjectId('6897d80622441912739d6c44'),
  'Produto': 'Lavadora de roupas',
  'Categoria do Produto': 'eletrodomesticos',
  'Preço': 2034.43,
  'Frete': 108.8583816384,
  'Data da Compra': '01/03/2021',
  'Vendedor': 'Thiago Silva',
  'Local da compra': 'RS',
  'Avaliação da compra': 5,
  'Tipo de pagamento': 'cartao_credito',
  'Quantidade de parcelas': 2,
  'Latitude': -30.17,
  'Longitude': -53.5},
 {'_id': ObjectId('6897d80622441912739d6c45'),

In [17]:
import pandas as pd

df_produtos = pd.DataFrame(lista_produtos)
df_produtos.head()

,_id,Produto,Categoria do Produto,Preço,Frete,Data da Compra,Vendedor,Local da compra,Avaliação da compra,Tipo de pagamento,Quantidade de parcelas,Latitude,Longitude
0,6897d80622441912739d6c08,Xadrez de madeira,brinquedos,25.23,0.000000,01/01/2021,Thiago Silva,BA,5,cartao_credito,2,-13.29,-41.71
1,6897d80622441912739d6c09,Impressora,eletronicos,322.04,14.732100,01/01/2021,João Souza,SP,3,cartao_credito,1,-22.19,-48.79
2,6897d80622441912739d6c0a,Mesa de centro,moveis,282.22,12.611805,01/01/2021,João Souza,SP,3,boleto,1,-22.19,-48.79
3,6897d80622441912739d6c0b,Tablet ABXY,eletronicos,1100.42,68.451348,01/01/2021,Beatriz Moraes,SP,1,cupom,1,-22.19,-48.79
4,6897d80622441912739d6c0c,Fogão,eletrodomesticos,791.81,42.444626,01/01/2021,Juliana Costa,SP,4,boleto,1,-22.19,-48.79

**Formatando as datas**

In [18]:
df_produtos["Data da Compra"] = pd.to_datetime(df_produtos["Data da Compra"], format="%d/%m/%Y")
df_produtos["Data da Compra"] = df_produtos["Data da Compra"].dt.strftime("%Y-%m-%d")
df_produtos.head()

,_id,Produto,Categoria do Produto,Preço,Frete,Data da Compra,Vendedor,Local da compra,Avaliação da compra,Tipo de pagamento,Quantidade de parcelas,Latitude,Longitude
0,6897d80622441912739d6c08,Xadrez de madeira,brinquedos,25.23,0.000000,2021-01-01,Thiago Silva,BA,5,cartao_credito,2,-13.29,-41.71
1,6897d80622441912739d6c09,Impressora,eletronicos,322.04,14.732100,2021-01-01,João Souza,SP,3,cartao_credito,1,-22.19,-48.79
2,6897d80622441912739d6c0a,Mesa de centro,moveis,282.22,12.611805,2021-01-01,João Souza,SP,3,boleto,1,-22.19,-48.79
3,6897d80622441912739d6c0b,Tablet ABXY,eletronicos,1100.42,68.451348,2021-01-01,Beatriz Moraes,SP,1,cupom,1,-22.19,-48.79
4,6897d80622441912739d6c0c,Fogão,eletrodomesticos,791.81,42.444626,2021-01-01,Juliana Costa,SP,4,boleto,1,-22.19,-48.79

In [19]:
df_produtos.to_csv("../data/tabela_2021_em_diante.csv", index = False)

In [20]:
client.close()